# Generated by Django 4.2.30 on 2026-07-23 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('avatar_color', models.CharField(default='#5b5bf0', max_length=16)),
                ('kids', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MyListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='accounts.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_by', to='catalog.title')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('profile', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ContinueWatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_items', to='accounts.profile')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continue_by', to='catalog.title')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('profile', 'title')},
            },
        ),
    ]
