"""Catalog seed data — mirrors the Signal frontend demo catalog."""

def pic(seed: str, w: int, h: int) -> str:
    return f'https://picsum.photos/seed/{seed}/{w}/{h}'


TITLES = [
    {
        'slug': 'big-buck-bunny',
        'title': 'Big Buck Bunny',
        'description': 'A giant rabbit with a heart bigger than himself faces three bullying rodents in a comedy adventure that launched open movie history.',
        'type': 'movie',
        'year': 2008,
        'rating': 'PG',
        'duration': '10m',
        'genres': ['Animation', 'Comedy', 'Family'],
        'match_score': 98,
        'poster_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/500px-Big_buck_bunny_poster_big.jpg',
        'backdrop_url': pic('bbb-bg', 1280, 720),
        'trailer_url': '/videos/big-buck-bunny.mp4',
        'video_url': '/videos/big-buck-bunny.mp4',
        'accent_from': '#2d6a4f',
        'accent_to': '#95d5b2',
        'featured': True,
        'trending': True,
        'cast': ['Sacha Goedegebure', 'Andy Goralczyk'],
    },
    {
        'slug': 'elephants-dream',
        'title': 'Elephants Dream',
        'description': 'Two strange characters explore a surreal mechanical world in the first open movie ever produced with Blender.',
        'type': 'movie',
        'year': 2006,
        'rating': 'PG',
        'duration': '11m',
        'genres': ['Animation', 'Sci-Fi', 'Drama'],
        'match_score': 91,
        'poster_url': pic('elephants-dream', 400, 600),
        'backdrop_url': pic('elephants-dream-bg', 1280, 720),
        'trailer_url': '/videos/flower.mp4',
        'video_url': '/videos/flower.mp4',
        'accent_from': '#3d348b',
        'accent_to': '#7678ed',
        'trending': True,
        'cast': ['Tygo Gernandt', 'Cas Jansen'],
    },
    {
        'slug': 'sintel',
        'title': 'Sintel',
        'description': 'A lonely young woman searches for a baby dragon she raised, in a sweeping fantasy short that redefined open animation.',
        'type': 'movie',
        'year': 2010,
        'rating': 'PG-13',
        'duration': '15m',
        'genres': ['Animation', 'Fantasy', 'Adventure'],
        'match_score': 96,
        'poster_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Sintel_poster.jpg/500px-Sintel_poster.jpg',
        'backdrop_url': pic('sintel-bg', 1280, 720),
        'trailer_url': '/videos/sintel.mp4',
        'video_url': '/videos/sintel.mp4',
        'accent_from': '#6a040f',
        'accent_to': '#e85d04',
        'featured': True,
        'trending': True,
        'cast': ['Halina Reijn', 'Thom Hoffman'],
    },
    {
        'slug': 'tears-of-steel',
        'title': 'Tears of Steel',
        'description': 'In a dystopian Amsterdam, a group of warriors and scientists try to stop an army of robots from destroying the city.',
        'type': 'movie',
        'year': 2012,
        'rating': 'PG-13',
        'duration': '12m',
        'genres': ['Sci-Fi', 'Action', 'Drama'],
        'match_score': 88,
        'poster_url': pic('tears-of-steel', 400, 600),
        'backdrop_url': pic('tears-of-steel-bg', 1280, 720),
        'trailer_url': '/videos/sintel-trailer.mp4',
        'video_url': '/videos/sintel-trailer.mp4',
        'accent_from': '#212529',
        'accent_to': '#adb5bd',
        'trending': True,
        'cast': ['Derek de Lint', 'Sergio Hasselbaink', 'Vanja Rukavina'],
    },
    {
        'slug': 'for-bigger-blazes',
        'title': 'For Bigger Blazes',
        'description': 'A high-octane promotional short that captures the thrill of speed, fire, and cinematic scale in under a minute.',
        'type': 'movie',
        'year': 2015,
        'rating': 'G',
        'duration': '15s',
        'genres': ['Action', 'Short'],
        'match_score': 84,
        'poster_url': pic('bigger-blazes', 400, 600),
        'backdrop_url': pic('bigger-blazes-bg', 1280, 720),
        'trailer_url': '/videos/jellyfish.mp4',
        'video_url': '/videos/jellyfish.mp4',
        'accent_from': '#9b2226',
        'accent_to': '#ee9b00',
        'new_release': True,
        'cast': ['Chromecast Studio'],
    },
    {
        'slug': 'for-bigger-escapes',
        'title': 'For Bigger Escapes',
        'description': 'Escape into a world of adventure with this vibrant short that celebrates exploration and cinematic freedom.',
        'type': 'movie',
        'year': 2015,
        'rating': 'G',
        'duration': '15s',
        'genres': ['Adventure', 'Short'],
        'match_score': 82,
        'poster_url': pic('bigger-escapes', 400, 600),
        'backdrop_url': pic('bigger-escapes-bg', 1280, 720),
        'trailer_url': '/videos/sample.mp4',
        'video_url': '/videos/sample.mp4',
        'accent_from': '#0077b6',
        'accent_to': '#90e0ef',
        'new_release': True,
        'cast': ['Chromecast Studio'],
    },
    {
        'slug': 'for-bigger-fun',
        'title': 'For Bigger Fun',
        'description': 'A playful, colorful short packed with energy — perfect for anyone who wants pure entertainment.',
        'type': 'movie',
        'year': 2015,
        'rating': 'G',
        'duration': '60s',
        'genres': ['Comedy', 'Family', 'Short'],
        'match_score': 90,
        'poster_url': pic('bigger-fun', 400, 600),
        'backdrop_url': pic('bigger-fun-bg', 1280, 720),
        'trailer_url': '/videos/big-buck-bunny.mp4',
        'video_url': '/videos/big-buck-bunny.mp4',
        'accent_from': '#7209b7',
        'accent_to': '#f72585',
        'cast': ['Chromecast Studio'],
    },
    {
        'slug': 'for-bigger-joyrides',
        'title': 'For Bigger Joyrides',
        'description': 'Buckle up for a high-speed joyride through stunning landscapes and pulse-pounding thrills.',
        'type': 'movie',
        'year': 2015,
        'rating': 'G',
        'duration': '15s',
        'genres': ['Action', 'Adventure', 'Short'],
        'match_score': 87,
        'poster_url': pic('bigger-joyrides', 400, 600),
        'backdrop_url': pic('bigger-joyrides-bg', 1280, 720),
        'trailer_url': '/videos/flower.mp4',
        'video_url': '/videos/flower.mp4',
        'accent_from': '#d00000',
        'accent_to': '#ffba08',
        'trending': True,
        'cast': ['Chromecast Studio'],
    },
    {
        'slug': 'for-bigger-meltdowns',
        'title': 'For Bigger Meltdowns',
        'description': 'When things heat up, only the bold survive. An intense short that pushes cinematic limits.',
        'type': 'movie',
        'year': 2015,
        'rating': 'PG',
        'duration': '15s',
        'genres': ['Thriller', 'Action', 'Short'],
        'match_score': 85,
        'poster_url': pic('bigger-meltdowns', 400, 600),
        'backdrop_url': pic('bigger-meltdowns-bg', 1280, 720),
        'trailer_url': '/videos/jellyfish.mp4',
        'video_url': '/videos/jellyfish.mp4',
        'accent_from': '#370617',
        'accent_to': '#dc2f02',
        'cast': ['Chromecast Studio'],
    },
    {
        'slug': 'subaru-outback',
        'title': 'Subaru Outback — On the Road',
        'description': 'Hit the open road in this cinematic automotive short that celebrates freedom, design, and the journey itself.',
        'type': 'movie',
        'year': 2016,
        'rating': 'G',
        'duration': '2m',
        'genres': ['Documentary', 'Short'],
        'match_score': 79,
        'poster_url': pic('subaru-outback', 400, 600),
        'backdrop_url': pic('subaru-outback-bg', 1280, 720),
        'trailer_url': '/videos/sample.mp4',
        'video_url': '/videos/sample.mp4',
        'accent_from': '#1b4332',
        'accent_to': '#52b788',
        'cast': ['Subaru'],
    },
    {
        'slug': 'volkswagen-gtis',
        'title': 'Volkswagen GTI Review',
        'description': 'A sharp look at performance and style — the GTI redefined in a sleek short-form review experience.',
        'type': 'movie',
        'year': 2016,
        'rating': 'G',
        'duration': '2m',
        'genres': ['Documentary', 'Short'],
        'match_score': 76,
        'poster_url': pic('vw-gti', 400, 600),
        'backdrop_url': pic('vw-gti-bg', 1280, 720),
        'trailer_url': '/videos/sintel.mp4',
        'video_url': '/videos/sintel.mp4',
        'accent_from': '#10002b',
        'accent_to': '#7b2cbf',
        'cast': ['Garage Studio'],
    },
    {
        'slug': 'we-are-going-on-bullrun',
        'title': 'We Are Going on Bullrun',
        'description': 'Join an epic cross-country rally of supercars, friendship, and pure adrenaline.',
        'type': 'movie',
        'year': 2017,
        'rating': 'PG',
        'duration': '2m',
        'genres': ['Action', 'Documentary', 'Adventure'],
        'match_score': 93,
        'poster_url': pic('bullrun', 400, 600),
        'backdrop_url': pic('bullrun-bg', 1280, 720),
        'trailer_url': '/videos/sintel-trailer.mp4',
        'video_url': '/videos/sintel-trailer.mp4',
        'accent_from': '#03045e',
        'accent_to': '#00b4d8',
        'trending': True,
        'new_release': True,
        'cast': ['Bullrun Crew'],
    },
    {
        'slug': 'what-car-can-you-get',
        'title': 'What Car Can You Get for a Grand?',
        'description': 'A fun, practical guide to finding the best wheels on a budget — comedy and car culture collide.',
        'type': 'series',
        'year': 2018,
        'rating': 'TV-PG',
        'duration': '3m',
        'genres': ['Comedy', 'Reality', 'Documentary'],
        'match_score': 81,
        'poster_url': pic('car-grand', 400, 600),
        'backdrop_url': pic('car-grand-bg', 1280, 720),
        'trailer_url': '/videos/jellyfish.mp4',
        'video_url': '/videos/jellyfish.mp4',
        'accent_from': '#264653',
        'accent_to': '#e9c46a',
        'seasons': 1,
        'cast': ['Auto Experts'],
    },
    {
        'slug': 'cosmos-journey',
        'title': 'Cosmos Journey',
        'description': 'Travel beyond the stars in this immersive visual voyage through nebulae, galaxies, and the unknown.',
        'type': 'series',
        'year': 2023,
        'rating': 'TV-G',
        'duration': '45m',
        'genres': ['Documentary', 'Sci-Fi'],
        'match_score': 94,
        'poster_url': pic('cosmos-journey', 400, 600),
        'backdrop_url': pic('cosmos-journey-bg', 1280, 720),
        'trailer_url': '/videos/big-buck-bunny.mp4',
        'video_url': '/videos/big-buck-bunny.mp4',
        'accent_from': '#0d1b2a',
        'accent_to': '#415a77',
        'seasons': 3,
        'new_release': True,
        'featured': True,
        'cast': ['Narrator Ensemble'],
    },
    {
        'slug': 'night-city',
        'title': 'Night City',
        'description': 'Neon lights, rain-soaked streets, and secrets that never sleep — a stylish crime thriller series.',
        'type': 'series',
        'year': 2024,
        'rating': 'TV-MA',
        'duration': '52m',
        'genres': ['Thriller', 'Crime', 'Drama'],
        'match_score': 95,
        'poster_url': pic('night-city', 400, 600),
        'backdrop_url': pic('night-city-bg', 1280, 720),
        'trailer_url': '/videos/sintel-trailer.mp4',
        'video_url': '/videos/sintel-trailer.mp4',
        'accent_from': '#240046',
        'accent_to': '#7b2cbf',
        'seasons': 2,
        'trending': True,
        'new_release': True,
        'cast': ['Alex Rivera', 'Jordan Lee', 'Sam Okonkwo'],
    },
    {
        'slug': 'ocean-depths',
        'title': 'Ocean Depths',
        'description': 'Dive into the most mysterious places on Earth in this breathtaking nature documentary series.',
        'type': 'series',
        'year': 2022,
        'rating': 'TV-PG',
        'duration': '48m',
        'genres': ['Documentary', 'Nature'],
        'match_score': 97,
        'poster_url': pic('ocean-depths', 400, 600),
        'backdrop_url': pic('ocean-depths-bg', 1280, 720),
        'trailer_url': '/videos/sintel.mp4',
        'video_url': '/videos/sintel.mp4',
        'accent_from': '#023e8a',
        'accent_to': '#48cae4',
        'seasons': 4,
        'featured': True,
        'cast': ['Marine Biologists'],
    },
    {
        'slug': 'kitchen-wars',
        'title': 'Kitchen Wars',
        'description': 'Top chefs battle under pressure in the ultimate culinary competition. Heat, hustle, and haute cuisine.',
        'type': 'series',
        'year': 2024,
        'rating': 'TV-14',
        'duration': '42m',
        'genres': ['Reality', 'Comedy'],
        'match_score': 89,
        'poster_url': pic('kitchen-wars', 400, 600),
        'backdrop_url': pic('kitchen-wars-bg', 1280, 720),
        'trailer_url': '/videos/big-buck-bunny.mp4',
        'video_url': '/videos/big-buck-bunny.mp4',
        'accent_from': '#bc4749',
        'accent_to': '#f2e8cf',
        'seasons': 5,
        'new_release': True,
        'cast': ['Chef Marco', 'Chef Yuki', 'Host Dana'],
    },
    {
        'slug': 'shadow-protocol',
        'title': 'Shadow Protocol',
        'description': 'An elite spy must stop a global conspiracy before time runs out. Espionage at its most intense.',
        'type': 'movie',
        'year': 2023,
        'rating': 'R',
        'duration': '2h 8m',
        'genres': ['Action', 'Thriller', 'Mystery'],
        'match_score': 92,
        'poster_url': pic('shadow-protocol', 400, 600),
        'backdrop_url': pic('shadow-protocol-bg', 1280, 720),
        'trailer_url': '/videos/sintel-trailer.mp4',
        'video_url': '/videos/sintel-trailer.mp4',
        'accent_from': '#0b090a',
        'accent_to': '#5c677d',
        'trending': True,
        'cast': ['Morgan Blake', 'Priya Shah', 'Chris Dunn'],
    },
    {
        'slug': 'laugh-track',
        'title': 'Laugh Track',
        'description': 'A failed stand-up comic finds unexpected fame — and chaos — when his life becomes a live sitcom.',
        'type': 'series',
        'year': 2021,
        'rating': 'TV-14',
        'duration': '28m',
        'genres': ['Comedy', 'Drama'],
        'match_score': 86,
        'poster_url': pic('laugh-track', 400, 600),
        'backdrop_url': pic('laugh-track-bg', 1280, 720),
        'trailer_url': '/videos/sample.mp4',
        'video_url': '/videos/sample.mp4',
        'accent_from': '#f77f00',
        'accent_to': '#fcbf49',
        'seasons': 3,
        'cast': ['Jamie Cole', 'Riley Fox'],
    },
    {
        'slug': 'ember-peak',
        'title': 'Ember Peak',
        'description': 'A family returns to their mountain hometown and uncovers a legend that was never meant to be found.',
        'type': 'movie',
        'year': 2024,
        'rating': 'PG-13',
        'duration': '1h 54m',
        'genres': ['Horror', 'Mystery', 'Thriller'],
        'match_score': 88,
        'poster_url': pic('ember-peak', 400, 600),
        'backdrop_url': pic('ember-peak-bg', 1280, 720),
        'trailer_url': '/videos/flower.mp4',
        'video_url': '/videos/flower.mp4',
        'accent_from': '#1a1423',
        'accent_to': '#3d348b',
        'new_release': True,
        'cast': ['Elena Vargas', 'Tom Briggs'],
    },
]
