# Generated by Django 4.2.30 on 2026-07-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=16)),
                ('year', models.PositiveIntegerField()),
                ('rating', models.CharField(blank=True, max_length=32)),
                ('duration', models.CharField(blank=True, max_length=32)),
                ('match_score', models.PositiveSmallIntegerField(default=80)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('backdrop_url', models.URLField(blank=True, max_length=500)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('accent_from', models.CharField(default='#333333', max_length=16)),
                ('accent_to', models.CharField(default='#666666', max_length=16)),
                ('featured', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('new_release', models.BooleanField(default=False)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('seasons', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', 'title'],
            },
        ),
    ]
